language: python

cache:
  - pip

python:
  - '3.7'
  - '2.7'

addons:
  apt:
    update: true

install:
  - pip install --upgrade pip setuptools wheel
  - pip install .

script:
  - pip install hacking pytest
  - flake8 .
  - pytest -v tests

sudo: false

branches:
  only:
    - master
